### ISSUE TITLE
NPM Package not found

### ISSUE THREAD

**Issue by AlexandrKoliukh** [JS-DevTools/ono#14]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@jsdevtools%2fono - Not found
npm ERR! 404 
npm ERR! 404  '@jsdevtools/ono@^7.1.3' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@apidevtools/json-schema-ref-parser'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by JamesMessinger** [comment]
This is a problem with NPM.  You can track the issue here:

https://status.npmjs.org/incidents/cksjqc1w11v5
